### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#1338]
Hard to explain but it feels like there's 2 different instances of chat happening simultaneously, and refreshing shifts between them. Refer to the videos for a clear view of the issue. Refreshing CSS, JS, doing hard refreshes and even using an incognito browser does not fix the issue.

https://user-images.githubusercontent.com/61713323/197621486-a542a18f-36a1-4bff-8938-f542198f62f9.mp4

https://user-images.githubusercontent.com/61713323/197621510-6c9c2a65-c795-4f77-9964-c29f489bb2ca.mp4

**Comment by f8daniel** [comment]
There should be a fix coming for the chat issue.
Whenever you render the chat log, you store a local copy of the last 50 messages, so that way when you reconnect to saito you have some stuff in your chat. Meanwhile, it checks with the server for the last 50 (theoretically to catch newer messages from when you were disconnected). 
There were two (potential) issues. One is I was only keeping 50 messages locally and querying 100 messages from the server, so you may be flushed with older messages. Two was that I was not checking the timestamps so that those older messages were treated as newer messages and added to the bottom of the chat. 

This shouldn't happen after the next server reset, but let me know if it does.

**Comment by f8daniel** [comment]
@Rammko please test and close if fixed

**Comment by Rammko** [comment]
![image](https://user-images.githubusercontent.com/61713323/198121657-2428d32e-f83f-4684-a063-ef87b06f1eae.png)

**Comment by Rammko** [comment]
![image](https://user-images.githubusercontent.com/61713323/198121757-6e56f777-6adb-46ea-9433-d900e6de168d.png)

**Comment by f8daniel** [comment]
@Rammko what is the comment? Dark mode css isn't user friendly? We don't have dark mode yet. make a new issue
