### ISSUE TITLE
Appstore app loading is slow

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#158]
Steps:
1. Click on the appstore
2.

**Comment by trevelyan** [comment]
This issue is solved. We have a new cache that can be used to prevent frequent database queries.

There are speed issues when the browser is still connecting to the network to download blocks. Once those blocks have downloaded everything is quite fast now.

The long-term solution will be redesigning the APPSTORE plugin page, so that searching can be done independently of opening the appstore itself.
