### ISSUE TITLE
HIS 2P: initial Papal hand size and other issues

### ISSUE THREAD

**Issue by JoelCFC25** [SaitoTech/saito-lite-rust#2588]
https://github.com/SaitoTech/saito-lite-rust/blob/2ef7258a689f276a21e2392267b4d87148b3e0ce/mods/his/src/factions/papacy.js#L26

Not sure why I didn't notice previously, but the Papacy is starting with too many cards (2 home and 4 event for a total of 6), and I wonder if this line is why. It appears to be referencing England's total when determining the Papacy's starting hand size? When viewing the Papal power card at the outset of the game, only 1 key marker is shown missing, but it should be 2 to reflect initial control of Rome and Ravenna--so the "3 cards / 4 VP" box should be the rightmost empty one. 

The St Peter's VP track is showing the "St Peter's CP" marker instead of the VP marker. 

Unrest is still a little wonky. I did some Reformation attempts using Carlstadt and failed, leaving a Protestant home space in unrest but still under Catholic religious influence. Before Schmalkaldic League formation, It should be permissible for the Protestant player to remove unrest here while it's still Catholic--see item `b.` in Removing Unrest in 12.4 on page 17 (no adjacency of units is required in this case). 

EDIT: After using the _Andrea Doria_ diplomacy card as the Papacy to activate Genoa, Bastia should show a Papal hex control marker. It's almost never going to be impactful, but it would be technically correct (and maybe an opportunity to check of activation of other minors puts HCMs on unfortified spaces, e.g. if the Papacy activates Venice).

**Comment by trevelyan** [comment]
all above issues now fixed in staging on github

( thanks )

will get pushed to staging server within a day or so

FYI - we've got Combat and Response cards *mostly* implemented now although probably difficult to test in 2P game.

hoping to be stable enough to test with some public games soon

<img width="208" alt="Screenshot 2567-09-08 at 14 04 02" src="https://github.com/user-attachments/assets/fa2abf61-0008-4be4-8464-34b8228c3361">
