### ISSUE TITLE
HIS 2P: translation debater bonus possibility skipped, plus Luther sub issue

### ISSUE THREAD

**Issue by JoelCFC25** [SaitoTech/saito-lite-rust#2591]
Appreciate your diving into all of these. I've started a new game and noticed: 

* Playing a card for CP as Protestant, then choosing to Translate Scripture--before it gave me a prompt when applicable to boost the action results (e.g., with Melanchthon or Luther in the German zone). That now seems to get skipped--it just performs however many CP of translation you select without the prompt to boost with an uncommitted debater
* I've got a hanging prompt on both sides. Here's the sequence that led to it:
1. Papacy plays _Leipzig Debate_, chooses committed pool (only Carlstadt). Selects Eck as attacker.
2. Protestant intervenes with _Here I Stand_ home card to sub in Luther
3. Debate resolves, Papacy wins, is prompted to flip some spaces back to Catholic
4. From there, the Protestant sees a "Papacy calling Theological Debate" prompt from which they can't proceed (nothing to click on). The Papacy sees a "Protestant player turn" or similar prompt with nothing to click on. Both sides are hung with no way to advance the play.

**Comment by trevelyan** [comment]
first problem solved -- translation bonuses should be back.

a slew of other minor fixes over the last couple of days as well from the 3P evening test games we are having.

things are getting much more stable -- combat and response cards haven't knocked us out for a while too

had trouble replicating the second issue with Leipzig Debate, but it might easily have been fixed in the course of the other patches that have gone live in the last 3-4 days, and possibly the translation issue as well, so will treat as closed by keep an eye out for issues here.
