### ISSUE TITLE
Twilight Struggle - No second guessing

### ISSUE THREAD

**Issue by Rammko** [SaitoTech/saito-lite-rust#341]
The arrow to go back after a card is selected in order to "Second Guess" is not working, clicking on it after selecting a card does nothing.

![image](https://user-images.githubusercontent.com/61713323/161400484-1936f231-98a0-4a90-9744-c19e6cb6a899.png)

**Comment by trevelyan** [comment]
Closing as we need more detailed instructions on how to replicate this problem.

Does this apply to all cards? Specific cards?

What is the exact sequence that is clicked on the menu in order to get to the point

Please provide detailed bugs. And screenshot the entire page including the log for obvious reasons. Our development team cannot intuit what is happening with this sort of bug report.
