### ISSUE TITLE
Test 1: Dealer Wins Ties

### ISSUE THREAD

**Issue by noslrac27** [SaitoTech/saito-lite-rust#350]
Module: Arcade/Blackjack

Test Steps: 
1. The dealer wins via tiebreaker at the end of round 2. 
2. The popup notification of the round ending appeared.
3. I clicked outside the popup but the game didn't proceed to round 3.

Screenshot
<img width="960" alt="Black Jack Round 3" src="https://user-images.githubusercontent.com/101871246/161586154-41e6fbd3-9875-4f9f-8de3-9e3169e38712.png">

Other information:
- Device Used: Laptop/Web Browser
- OS: Windows 11
- Browser: Chrome Incognito and Avast Secure Browser
- Version: Version 100.0.4896.60 (Official Build) (64-bit) and Version 99.0.15283.83 (Official Build) (64-bit)

**Comment by Rammko** [comment]
I was able to get to round 4 and beyond without issue, on different games. Also unless house rules state otherwise, a dealer should not win in case of a tie, the bet should be returned to the players who tied with him.

![image](https://user-images.githubusercontent.com/61713323/161663261-48510d61-e79c-4d32-a38d-9ce422c3acca.png)

**Comment by noslrac27** [comment]
I didn't encounter being stuck again.
However, Rammko mentioned the Dealer should not be winning ties. It happened again.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/101871246/161970336-3461aa94-5f75-4d62-84aa-e2afd2c1b266.png">
