### ISSUE TITLE
Wordblock: Creating a word parallel to existing words only provide score to the newly created

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#409]
Test Step
1. Create a word parallel to existing words
2. Submit the word
3. Check the score; only the new word is calculated and reflected as a score, the other words created from the existing words are not counted

e.g. in the screenshot, the word AN, DO and EN are not added as points

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/96273856/163790007-834e90c8-f491-497a-befd-f559b494c73e.png">

**Comment by f8daniel** [comment]
![image](https://user-images.githubusercontent.com/70703104/163795704-a7b479e0-2784-476b-9d8e-db488f5df769.png)

**Comment by f8daniel** [comment]
This is a user feedback problem rather than a game problem.
Proposed solution: a brief pseudo animation that "lights up" each of the tiles as the game calculates the points for the play. Bonus, add moving numbers on the screen to show the math during the animation (e.g. numbers float from the position above the tile to a big glowing number keeping track of the running total).

**Comment by karlsaito** [comment]
Adding them to the logs should be enough @f8daniel , updating the logs to show the words have been accounted.

**Comment by estapeluo** [comment]
Closing as per #474 merge - This is a nice QOL, agreed with he purpose of the headword on sidebar logs.
