### ISSUE TITLE
Rejoining private game created via shared link throws "game no longer available" notification

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#470]
Test Steps:
1. User A creates a private game for 3 players
2. User A shares the link to User B
3. User B joins via the link shared
4. Error 1 **User B click the cancel button, User B avatar is still shown on the game room**
5. User B rejoins using the link shared
6. **Error 2: Screen prompts "game no longer available"  on User B,**

Expected on Step 6:
For Error 1:  When user B triggered the cancel button, user B should be removed on the game room

For Error 2: User B should be able to rejoin on the game room

User A view when User B triggered the cancel button: (Error 1)
<img width="767" alt="image" src="https://user-images.githubusercontent.com/96273856/166248147-aef96853-b1a2-4a3d-8b94-ec4c6ff496f6.png">

User B view:  (Error 2)
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/96273856/166247765-384d0c00-9006-49ba-be00-799ace91dd0b.png">

**Comment by estapeluo** [comment]
Back in the old days of Arcade V1... the cancel button mechanic was a direct game end behavior and removed the game off the wallets.

Probably for 3+ games, add additional behavior for the cancel button where it just removed just the player and not cancel (end) the whole game. Rename cancel as resign?

**Comment by f8daniel** [comment]
I wonder if the testers understand the expected behavior.
Cancel can do three things:
1) If I create an game invite, I can cancel the invitation.
2) If I join someone else's game invite (3+ player) before the game loader launches, I can "cancel" to quit the game without deleting the game invitation.
3) If the game is initialized, I can go to the arcade and click cancel to resign from the game and fast forward the game to a game over state.

**Comment by estapeluo** [comment]
Closing, expected cancel and rejoin via click/url is working for 3p.
