### ISSUE TITLE
Fix endless loop in poker receivePayment

### ISSUE THREAD

**Issue by umairkhannn** [SaitoTech/saito-lite-rust#544]
![Screenshot from 2022-05-18 12-03-00](https://user-images.githubusercontent.com/104337801/168996746-e9bae17e-c1c7-4ca9-a876-e653271f5552.png)

![image](https://user-images.githubusercontent.com/104337801/168993727-87fdd094-68b9-4f95-9155-3286896e353e.png)
![image](https://user-images.githubusercontent.com/104337801/168994229-ce023912-4ec1-4363-8f8d-19031974978a.png)

Payment goes through but stuck in loop when trying to find the payment.

lib\saito\wallet.ts:
 1208      };
 1209  
 1210:     const poll_check_payment_function = async () => {
 1211:       console.log("poll_check_payment_function remaining tries: " + tries);
 1212        let result = null;
 1213        try {
 ....
 1233          if (tries != 0) {
 1234            setTimeout(() => {
 1235:             poll_check_payment_function();
 1236            }, pollWaitTime);
 1237          } else {
 ....
 1248        }
 1249      };
 1250:     poll_check_payment_function();
 1251      //});
 1252    }

**Comment by trevelyan** [comment]
From discussions with Khan, this bug apparently surfaced in a 3P game, so there may be something in the order of payments (received) that is necessary for triggering this bug. Before we patch the issue (possible solution below) it would be useful to get more debugging information and see how common it is, particularly with 3P games.

It would certainly be useful to know if this issue is triggered only in N > 2 player games.

<img width="373" alt="Screen Shot 2565-05-19 at 09 52 22" src="https://user-images.githubusercontent.com/919135/169194209-40c508f8-1e41-49c2-977a-bd31abcef9c6.png">
<img width="361" alt="Screen Shot 2565-05-19 at 09 52 29" src="https://user-images.githubusercontent.com/919135/169194220-94c9a7a1-2c10-4b66-ac1f-6ee77ab23754.png">

**Comment by f8daniel** [comment]
Receive payments may still get stuck in an infinite loop, but the overlay now has an exit button so the user can close it and continue playing the game.
