### ISSUE TITLE
Saito Community returns DOMException error: DOMException: Failed to execute 'querySelector' on 'Document': '#7412fe97e34f5926a968079805535aee34fe567dc3c0ec7ecaa4fdb0b3e04e6e .chat-group-name' is not a valid selector.

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#828]
Test Steps:
1. Go to arcade
2. Click the Community Chatbox
3. Check the console: it returns this error
<img width="570" alt="image" src="https://user-images.githubusercontent.com/96273856/182069638-35c8b3a5-6b2b-46f6-a5d7-27ad90351258.png">

**Comment by f8daniel** [comment]
Sorry, it actually turns out to be a rather minor bug.
Cause:  html doesn't like id's that start with a number (TIL)
Effects: 
1) since someone helpfully wrapped the code in a try-catch block, it doesn't break anything.
2) We query the id only for the sake of logging in Matomo, though the catch also logs to Matomo
