### ISSUE TITLE
Settlers Suggestion: development card display

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#834]
This is in relation to issue 737 (https://github.com/SaitoTech/saito-lite-rust/issues/737)

Suggestion to make it easier for players to view development cards

Fig.1: Current display when purchasing development card (need to hover to read the description)
![aw](https://user-images.githubusercontent.com/107991527/182289211-ca1f23a8-e042-496f-96c5-6019e9b600bb.png)

Fig 2: Suggestion to add a separate text for the card description below (no need to hover)
![suggestion](https://user-images.githubusercontent.com/107991527/182289760-5d73f633-d163-4223-be2d-8b9a2bccc5f5.jpg)

@f8daniel

**Comment by f8daniel** [comment]
- Less text is generally better--cleaner look, easier styling. 
- Only novice players will need the hint about what the dev card does (experienced players will know just by seeing the title).
- Providing the instructions for the dev card in the UI is more likely to confuse players, who may click on it thinking they can play the card right away, which they cannot. I would anticipate bug reports that the game is broken because clicking "collect all cards..." doesn't do anything.
