### ISSUE TITLE
Dominion Improvements

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#881]
Improvements:
- [x] Card stack tracker/counter (to monitor the remaining available cards without hovering)
- [x] Magnified view of each card when hovered  (since it's hard to read the effects of each card)

Suggestions (for approval -- add below here):

- [ ] Add item here

**Comment by estapeluo** [comment]
- [ ] Small size img with good quality (or SVG with html text?)
- [ ] Able to explore what cards you have on your deck in details, in all the zones (deck, used, discard) and aswell able to see it after games ends.

**Comment by f8daniel** [comment]
@karlsaito I turned off default magnification of cards because it can be extremely annoying to constantly have them pop up in the screen when you are just trying to buy a Festival. You just have to click the compass in the HUD to toggle magnification on/off. 

@estapeluo Per game rules, you aren't allowed to look through your discard pile (in fact, you aren't even supposed to be able to count how many cards are there or in your deck). And, obviously, like every game in the world, you aren't supposed to be able to look through your deck and examine the top cards. Btw, "used" just means a temporary holding place for cards from your hand/top of deck before officially discarding them because some card rules don't want you reshuffle them while playing the event.

**Comment by estapeluo** [comment]
@f8daniel Probably I expressed myself wrong. If its against the rules then there's nothing to do - It is obvious that any card game you can't look at your deck unless its a card effect or w/e the game mechanic is.
But how about *after* game ends, where you can check your card selection for w/e reason? There's the log and players can card count offline/irl - but it might be a good feature.

**Comment by f8daniel** [comment]
@estapeluo Sure, it would be an interesting end-game splash screen to let you see the full details of every players deck, like the final stats in Settlers
